
cc_library(
    name = "funcs",
    srcs = ["Student.cpp", "StudentAfterFirstSession.cpp", "StudentAfterSecondSession.cpp"],
    hdrs = ["Student.hpp", "StudentAfterFirstSession.hpp", "StudentAfterSecondSession.hpp"],
    visibility = ["//visibility:public"]
)
