
cc_library(
    name = "funcs",
    srcs = ["LinkedList.cpp", "MyMatrix.cpp", "Myfraction.cpp"],
    hdrs = ["LinkedList.hpp", "MyMatrix.hpp", "Myfraction.hpp"],
    visibility = ["//visibility:public"]
)
