
cc_library(
    name = "funcs",
    srcs = ["Tree.cpp","ForestTree.cpp", "FruitTree.cpp", "TreeContainer.cpp"],
    hdrs = ["Tree.hpp","ForestTree.hpp", "FruitTree.hpp", "TreeContainer.hpp"],
    visibility = ["//visibility:public"]
)
